spring.application.name=BACnetFaultsAPI
spring.datasource.url=jdbc:postgresql://localhost:5432/bacnetalarms
spring.datasource.username=admin
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver
